/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WhyJaydeRouteImport } from './routes/why-jayde'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSlugRouteImport } from './routes/work_.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as CitiesRiyadhRouteImport } from './routes/cities/riyadh'
import { Route as CitiesQatarRouteImport } from './routes/cities/qatar'
import { Route as CitiesKuwaitRouteImport } from './routes/cities/kuwait'
import { Route as CitiesDubaiRouteImport } from './routes/cities/dubai'
import { Route as CitiesCairoRouteImport } from './routes/cities/cairo'
import { Route as BlogsSlugRouteImport } from './routes/blogs_.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyJaydeRoute = WhyJaydeRouteImport.update({
  id: '/why-jayde',
  path: '/why-jayde',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work_/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRiyadhRoute = CitiesRiyadhRouteImport.update({
  id: '/cities/riyadh',
  path: '/cities/riyadh',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesQatarRoute = CitiesQatarRouteImport.update({
  id: '/cities/qatar',
  path: '/cities/qatar',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesKuwaitRoute = CitiesKuwaitRouteImport.update({
  id: '/cities/kuwait',
  path: '/cities/kuwait',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesDubaiRoute = CitiesDubaiRouteImport.update({
  id: '/cities/dubai',
  path: '/cities/dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCairoRoute = CitiesCairoRouteImport.update({
  id: '/cities/cairo',
  path: '/cities/cairo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs_/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/blogs': typeof BlogsRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/why-jayde': typeof WhyJaydeRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cities/cairo': typeof CitiesCairoRoute
  '/cities/dubai': typeof CitiesDubaiRoute
  '/cities/kuwait': typeof CitiesKuwaitRoute
  '/cities/qatar': typeof CitiesQatarRoute
  '/cities/riyadh': typeof CitiesRiyadhRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/blogs': typeof BlogsRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/why-jayde': typeof WhyJaydeRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cities/cairo': typeof CitiesCairoRoute
  '/cities/dubai': typeof CitiesDubaiRoute
  '/cities/kuwait': typeof CitiesKuwaitRoute
  '/cities/qatar': typeof CitiesQatarRoute
  '/cities/riyadh': typeof CitiesRiyadhRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/blogs': typeof BlogsRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/why-jayde': typeof WhyJaydeRoute
  '/work': typeof WorkRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/blogs_/$slug': typeof BlogsSlugRoute
  '/cities/cairo': typeof CitiesCairoRoute
  '/cities/dubai': typeof CitiesDubaiRoute
  '/cities/kuwait': typeof CitiesKuwaitRoute
  '/cities/qatar': typeof CitiesQatarRoute
  '/cities/riyadh': typeof CitiesRiyadhRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/work_/$slug': typeof WorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/blogs'
    | '/projects'
    | '/quote'
    | '/why-jayde'
    | '/work'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/cities/cairo'
    | '/cities/dubai'
    | '/cities/kuwait'
    | '/cities/qatar'
    | '/cities/riyadh'
    | '/projects/$slug'
    | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/blogs'
    | '/projects'
    | '/quote'
    | '/why-jayde'
    | '/work'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/cities/cairo'
    | '/cities/dubai'
    | '/cities/kuwait'
    | '/cities/qatar'
    | '/cities/riyadh'
    | '/projects/$slug'
    | '/work/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/blogs'
    | '/projects'
    | '/quote'
    | '/why-jayde'
    | '/work'
    | '/blog_/$slug'
    | '/blogs_/$slug'
    | '/cities/cairo'
    | '/cities/dubai'
    | '/cities/kuwait'
    | '/cities/qatar'
    | '/cities/riyadh'
    | '/projects_/$slug'
    | '/work_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BlogsRoute: typeof BlogsRoute
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  WhyJaydeRoute: typeof WhyJaydeRoute
  WorkRoute: typeof WorkRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  CitiesCairoRoute: typeof CitiesCairoRoute
  CitiesDubaiRoute: typeof CitiesDubaiRoute
  CitiesKuwaitRoute: typeof CitiesKuwaitRoute
  CitiesQatarRoute: typeof CitiesQatarRoute
  CitiesRiyadhRoute: typeof CitiesRiyadhRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-jayde': {
      id: '/why-jayde'
      path: '/why-jayde'
      fullPath: '/why-jayde'
      preLoaderRoute: typeof WhyJaydeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/$slug': {
      id: '/work_/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/riyadh': {
      id: '/cities/riyadh'
      path: '/cities/riyadh'
      fullPath: '/cities/riyadh'
      preLoaderRoute: typeof CitiesRiyadhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/qatar': {
      id: '/cities/qatar'
      path: '/cities/qatar'
      fullPath: '/cities/qatar'
      preLoaderRoute: typeof CitiesQatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/kuwait': {
      id: '/cities/kuwait'
      path: '/cities/kuwait'
      fullPath: '/cities/kuwait'
      preLoaderRoute: typeof CitiesKuwaitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/dubai': {
      id: '/cities/dubai'
      path: '/cities/dubai'
      fullPath: '/cities/dubai'
      preLoaderRoute: typeof CitiesDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/cairo': {
      id: '/cities/cairo'
      path: '/cities/cairo'
      fullPath: '/cities/cairo'
      preLoaderRoute: typeof CitiesCairoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs_/$slug': {
      id: '/blogs_/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BlogsRoute: BlogsRoute,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  WhyJaydeRoute: WhyJaydeRoute,
  WorkRoute: WorkRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  CitiesCairoRoute: CitiesCairoRoute,
  CitiesDubaiRoute: CitiesDubaiRoute,
  CitiesKuwaitRoute: CitiesKuwaitRoute,
  CitiesQatarRoute: CitiesQatarRoute,
  CitiesRiyadhRoute: CitiesRiyadhRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
